[aws]
aws_access_key_id = "AKIAT2UAZPWABQQXR4G6"
aws_secret_access_key = "b+q6/InBKkYztnbdNBYO0mrQffW3skb7RfFMVza2"
region = "us-east-1"
[gcp_service_account]
type = "service_account"
project_id = "christos-bill"
private_key_id = "your-private-key-id-here"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCx8tiZKRIJsYcJ
nuWh5beDZYK5+Qo/dSyoXZYUwYjTZHVVW51XqiVoYg8r093gR5o/H8jyz+3Gk1ZYU
rE0TfXK+xYR3etovJ+YF+Qp1LWkz6S5C9lS5/assoPKtcuxApbGHfo+5KBRT5fZY
0/tiYr2ouHQNZLjAn0uqKoiHosmizSERJH9BCury3uWT4/NRgTOnLjkNBzAoreQV
kl1CjmTxMLmfGgJLAi6eSURUlmazGV1zmml0UizspmGQ0YlFOIQHjXgr6qcS/Y81
NEzuaIq7C6gI/mCok0gYOyptgWn1mu5Dt+aoNFAXHUahoauJczapswVN9gl9IfFG
KuZP/LD3AgMBAAECggEAF7LX1c36cQALk+f1WfagM1ME6hvDPR19hZAnpMHvd9rI
OsKkVo/kR8+FgApVG00xaNeB7hZWlDU9v5MS0L2sQmvbsG3UEOOnZrQ8CE7768Xq
O1DDB+IYoeDtcNwVSqbGdd0NFwOXcXT20e2pVPkBeS7XhdEcKcsNMKRpembbo6qk
00W8Qsmdb4LUBSFS9QhUjgckfN5rghPeOLUTAmIdmveoI1eEh9iCtJoc6aw2msuZ
DBnyxldLEZz1KBPASygwX6BAvRstQ+B5GbnEGoreURX6cvvJAV78jwbVpR/xDhsD
5CcPafvtuHfQsr4Nj4U7qPF140SMKsx+vbxW9+12wQKBgQDrt4479/Ba2/QLgRwF
bNd4hp4CjhnYkgeSCfK6TQ2lAG+ilRFYu6DXMjWyOYiSqnlDXdpO80NzmTil0JGu
p3hic0DWb2KOmRiT3p8+nIKetbJlxLl613Y86cHuKTmnZkNH+1r8o/oSfaG8BzR5
+LiwM9l5iG1CoFeCarvQD+Y1OwKBgQDBQsBHQlx9/Rk1WjEMcg8NTUXBhh2rG7aA
myGFpN5f0hiFtGXSLDYXcr1pKoH4bt3vn2aAVR4rVnpwwDkJz/NqU0ih0FydyJFN
KmJvknTL/i7rLzPi2Y+cuJTJaHyb5oMALUq930o0jdKPsMEwOof7mk33Ge+RneLK
ievH/NlHdQKBgDyJPIccKuc6u9dEhizCgifa8rOXSP38quMPmP3NkiaBESqA/B58
uVbq9y1ZZ0C7dT8e2FUUVotWm1zCTte6/MjT7p/jpT0YBl7beqw6x7T41uMZ/cSV
lzEXm42NmtfqBHd1Dy348t1S1HmUpB57CPt/pWd36Q+GXFMLFEbf/nBHAoGBAL9d
V4O4JFnkypdXzYWjU2A6ib4NDUenU1mZQuJQ1JlRMlMCxGgOuykQxpliK/xR25Uw
45BjuFH1eZw32sLqlP9NpHgGGA9s0OP1+i68eMad1Nuwi9Iu19O5uiqNOgYthL4i
GwZUGehcHomF3mXhL1FmA5mQpvYrvqwLUdtfdc8ZAoGBANEHSGQQWILhq7BssTvA
9bnhMm3Pd2W/IfdYn2KjaXg0yaznn9w8TsHoqd7qNhTo0OxszJMqA0esiakWHYPX
hER5SFVP/P70a6L7W9pfEV7BJkE8Rn1H2eLMmFkaTFYUlrc+/MinhGQdaG2roD2D
lqCIw4p+Fd8zYDWB5rA8d2gQ
-----END PRIVATE KEY-----'''
client_email = "sheets-access-account@christos-bill.iam.gserviceaccount.com"
client_id = "101968118055667786184"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-access-account%40christos-bill.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
